apiVersion: apps/v1
kind: Deployment
metadata:
  name: convert-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: convert-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: convert-app
    spec:
      containers:
      - name: convert-app
        image: gcr.io/vivid-nomad-358913/convert:lastest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 100m
