name: CI/CD
on: 
  workflow_dispatch:
  release:
    types: [published, edited]
  push:
    branches: 
      - development
      - "release-**"    
 
env:
  DEPLOYMENT_NAME: api-4hub-faas
  IMAGE: api-4hub-faas
  ACR: ${{ secrets.REGISTRY_LOGIN_SERVER }}
  WEBAPP: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
jobs:
  buildTemplate:
    runs-on: ubuntu-latest
    steps:    
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v2
      - name: Checkout private tools
        uses: actions/checkout@v3
        with:
          repository: hirata11/devops-template
          path: template
      - name: templateBuiid  
        uses: ./template/build/api/api4i
        with:
          REGISTRY_LOGIN_SERVER:  ${{ secrets.REGISTRY_LOGIN_SERVER }}
          REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
          IMAGE: ${{ env.IMAGE }}
          ACR: ${{ env.ACR }}
          tag: dev
          git_token: ${{ secrets.GIT_ACCESS_TOKEN }}   
  deploy-dev:
    runs-on: ubuntu-latest
    needs: buildTemplate
    environment: development
    steps:
      - name: Checkout private tools
        uses: actions/checkout@v3
        with:
          repository: hirata11/devops-template
          path: template
      - name: templateDeploy  
        uses: ./template/deploy/api
        with:
          AZURE_CREDENTIALS:  ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          IMAGE: ${{ env.IMAGE }}
          ACR: ${{ env.ACR }}
          TAG: dev
          WEBAPP: ${{ env.WEBAPP }}           
