name: CI/CD
on: 
  workflow_dispatch:
  release:
    types: published
env:
  DEPLOYMENT_NAME: convert-app # nome da aplicação.
  IMAGE: convert #nome da imagem
  ACR: ${{ secrets.REGISTRY_LOGIN_SERVER }}
jobs:
  buildTemplate:
    runs-on: ubuntu-latest
    steps:    
      - id: latest
        uses: thebritican/fetch-latest-release@v2.0.0
        with:
          github_token: ${{ secrets.PAT }}    
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.latest.outputs.tag_name }}          
      - name: Checkout private tools
        uses: actions/checkout@v3
        with:
          repository: hirata11/devops-template
          token: ${{ secrets.PAT }} # `GH_PAT` is a secret that contains your PAT
          path: template
      - name: templateBuiid  
        uses: ./template/build/branch
        with:
          tag: ${{ steps.latest.outputs.tag_name }}
          token: ${{ secrets.PAT }}
      - name: templateBuiid  
        uses: ./template/build/api
        with:
          REGISTRY_LOGIN_SERVER:  ${{ secrets.REGISTRY_LOGIN_SERVER }}
          REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
          IMAGE: ${{ env.IMAGE }}
          ACR: ${{ env.ACR }}
          tag: ${{ steps.latest.outputs.tag_name }}          
  deploy-dev:
    runs-on: ubuntu-latest
    needs: buildTemplate
    environment: development
    steps:
      - id: latest
        uses: thebritican/fetch-latest-release@v2.0.0
        with:
          github_token: ${{ secrets.PAT }}
      - name: Checkout private tools
        uses: actions/checkout@v3
        with:
          repository: hirata11/devops-template
          token: ${{ secrets.PAT }} # `GH_PAT` is a secret that contains your PAT
          path: template
      - name: templateDeploy  
        uses: ./template/deploy/api
        with:
          AZURE_CREDENTIALS:  ${{ secrets.AZURE_CREDENTIALS }}
          IMAGE: ${{ env.IMAGE }}
          ACR: ${{ env.ACR }}
          TAG: ${{ steps.latest.outputs.tag_name }}          
  deploy-hml:
    runs-on: ubuntu-latest
    needs: deploy-dev
    environment: staging
    steps:
      - id: latest
        uses: thebritican/fetch-latest-release@v2.0.0
        with:
          github_token: ${{ secrets.PAT }}
      - name: Checkout private tools
        uses: actions/checkout@v3
        with:
          repository: hirata11/devops-template
          token: ${{ secrets.PAT }} # `GH_PAT` is a secret that contains your PAT
          path: template
      - name: templateDeploy  
        uses: ./template/deploy/api
        with:
          AZURE_CREDENTIALS:  ${{ secrets.AZURE_CREDENTIALS }}
          IMAGE: ${{ env.IMAGE }}
          ACR: ${{ env.ACR }}
          TAG: ${{ steps.latest.outputs.tag_name }}          
  deploy-prd:
      runs-on: ubuntu-latest
      needs: deploy-hml
      environment: production
      steps:
        - id: latest
          uses: thebritican/fetch-latest-release@v2.0.0
          with:
            github_token: ${{ secrets.PAT }}
        - name: Checkout private tools
          uses: actions/checkout@v3
          with:
            repository: hirata11/devops-template
            token: ${{ secrets.PAT }} # `GH_PAT` is a secret that contains your PAT
            path: template
        - name: templateDeploy  
          uses: ./template/deploy/api
          with:
            AZURE_CREDENTIALS:  ${{ secrets.AZURE_CREDENTIALS }}
            IMAGE: ${{ env.IMAGE }}
            ACR: ${{ env.ACR }}
            TAG: ${{ steps.latest.outputs.tag_name }}   
  rollbackprd:
      runs-on: ubuntu-latest
      needs: deploy-prd
      environment: rollback
      steps:
        - name: Checkout private tools
          uses: actions/checkout@v3
          with:
            repository: hirata11/devops-template
            token: ${{ secrets.PAT }}  
            path: template
        - id: latestdel
          uses: thebritican/fetch-latest-release@v2.0.0
          with:
            github_token: ${{ secrets.PAT }} 

        - name: getreleaseid  
          run: |
            release=$(curl \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.PAT }} " \
              https://api.github.com/repos/hirata11/${{ env.IMAGE }}/releases/tags/${{ steps.latestdel.outputs.tag_name }}  | jq '.id')
            echo $release
            curl \
              -X DELETE \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.PAT }} " \
              https://api.github.com/repos/hirata11/${{ env.IMAGE }}/releases/$release
          shell: bash

        - run: |
            sleep 1m
            curl -sL https://api.github.com/repos/hirata11/${{ env.IMAGE }}/releases/latest | jq -r ".tag_name"
          shell: bash

        - name: get lastest release
          id: lastestRelease
          run: echo "::set-output name=releasename::$(curl -sL https://api.github.com/repos/hirata11/${{ env.IMAGE }} /releases/latest | jq -r ".tag_name")"
        - name: templateDeploy  
          uses: ./template/deploy/api
          with:
            AZURE_CREDENTIALS:  ${{ secrets.AZURE_CREDENTIALS }}
            IMAGE: ${{ env.IMAGE }}
            ACR: ${{ env.ACR }}
            TAG: ${{ steps.lastestRelease.outputs.releasename }}   
  DeployProdOk:
      runs-on: ubuntu-latest
      needs: deploy-prd
      environment: production
      steps:
        - id: latest
          uses: thebritican/fetch-latest-release@v2.0.0
          with:
            github_token: ${{ secrets.PAT }}        
        - name:
          uses: tukasz/direct-merge-action@master
          with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            source-branch: 'release-${{ steps.latest.outputs.tag_name }}'
            target-branch: main
            commit-message: "Lliberada a versão ${{ steps.latest.outputs.tag_name }}"