name: CI/CD

on:
  push:
    branches:
      - development
      - "release-**"
      - azure01

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }} #ID do projeto no GCP
  GKE_CLUSTER: vivid-nomad-358913-gke    # Nome do cluster GKE.
  GKE_ZONE: us-central1   # Zona do cluster GKE.
  DEPLOYMENT_NAME: convert-app # nome da aplicação.
  IMAGE: convert #nome da imagem
  ACR: ${{ secrets.REGISTRY_LOGIN_SERVER }}

jobs:

  buildTemplate:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v2
      - name: Checkout private tools
        uses: actions/checkout@v3
        with:
          repository: hirata11/devops-template
          token: ${{ secrets.PAT }} # `GH_PAT` is a secret that contains your PAT
          path: template
        
      - name: templateBuiid  
        uses: ./template/build
        with:
          REGISTRY_LOGIN_SERVER:  ${{ secrets.REGISTRY_LOGIN_SERVER }}
          REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
          IMAGE: ${{ env.IMAGE }}
          ACR: ${{ env.ACR }}
          Env: $development
          
  deploy-dev:
    runs-on: ubuntu-latest
    needs: buildTemplate
    environment: development
    steps:
      - name: Checkout private tools
        uses: actions/checkout@v3
        with:
          repository: hirata11/devops-template
          token: ${{ secrets.PAT }} # `GH_PAT` is a secret that contains your PAT
          path: template

      - name: templateDeploy  
        uses: ./template/deploy
        with:
          AZURE_CREDENTIALS:  ${{ secrets.AZURE_CREDENTIALS }}
          IMAGE: ${{ env.IMAGE }}
          ACR: ${{ env.ACR }}
