name: CI/CD

on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
  release:
    types: [published, deleted]
  repository_dispatch:
    # this is the event_type passed in from the webhook, needs to match exactly what was defined in the webhook custom data payload
    types: [ "event-triggered-by-jira" ]
    


env:
  DEPLOYMENT_NAME: convert-app # nome da aplicação.
  IMAGE: convert #nome da imagem
  ACR: ${{ secrets.REGISTRY_LOGIN_SERVER }}

jobs:

  buildTemplate:
    runs-on: ubuntu-latest
    steps:    
      - id: latest
        uses: thebritican/fetch-latest-release@v1.0.3
        with:
          github_token: ${{ secrets.PAT }}
          
      - run: echo ${{ steps.latest.outputs.tag_name }}
    
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.latest.outputs.tag_name }}
          
      - name: Checkout private tools
        uses: actions/checkout@v3
        with:
          repository: hirata11/devops-template
          token: ${{ secrets.PAT }} # `GH_PAT` is a secret that contains your PAT
          path: template
        
      - name: templateBuiid  
        uses: ./template/build
        with:
          REGISTRY_LOGIN_SERVER:  ${{ secrets.REGISTRY_LOGIN_SERVER }}
          REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
          IMAGE: ${{ env.IMAGE }}
          ACR: ${{ env.ACR }}
          tag: ${{ steps.latest.outputs.tag_name }}
          
  deploy-dev:
    runs-on: ubuntu-latest
    needs: buildTemplate
    environment: development
    steps:
      - id: latest
        uses: thebritican/fetch-latest-release@v1.0.3
        with:
          github_token: ${{ secrets.PAT }}
      - name: Checkout private tools
        uses: actions/checkout@v3
        with:
          repository: hirata11/devops-template
          token: ${{ secrets.PAT }} # `GH_PAT` is a secret that contains your PAT
          path: template

      - name: templateDeploy  
        uses: ./template/deploy
        with:
          AZURE_CREDENTIALS:  ${{ secrets.AZURE_CREDENTIALS }}
          IMAGE: ${{ env.IMAGE }}
          ACR: ${{ env.ACR }}
          TAG: ${{ steps.latest.outputs.tag_name }}
          
  deploy-hml:
    runs-on: ubuntu-latest
    needs: deploy-dev
    environment: staging
    steps:
      - id: latest
        uses: thebritican/fetch-latest-release@v1.0.3
        with:
          github_token: ${{ secrets.PAT }}
      - name: Checkout private tools
        uses: actions/checkout@v3
        with:
          repository: hirata11/devops-template
          token: ${{ secrets.PAT }} # `GH_PAT` is a secret that contains your PAT
          path: template

      - name: templateDeploy  
        uses: ./template/deploy
        with:
          AZURE_CREDENTIALS:  ${{ secrets.AZURE_CREDENTIALS }}
          IMAGE: ${{ env.IMAGE }}
          ACR: ${{ env.ACR }}
          TAG: ${{ steps.latest.outputs.tag_name }}
          
  deploy-prd:
      runs-on: ubuntu-latest
      needs: deploy-hml
      environment: production
      steps:
        - id: latest
          uses: thebritican/fetch-latest-release@v1.0.3
          with:
            github_token: ${{ secrets.PAT }}
        - name: Checkout private tools
          uses: actions/checkout@v3
          with:
            repository: hirata11/devops-template
            token: ${{ secrets.PAT }} # `GH_PAT` is a secret that contains your PAT
            path: template

        - name: templateDeploy  
          uses: ./template/deploy
          with:
            AZURE_CREDENTIALS:  ${{ secrets.AZURE_CREDENTIALS }}
            IMAGE: ${{ env.IMAGE }}
            ACR: ${{ env.ACR }}
            TAG: ${{ steps.latest.outputs.tag_name }}
    
  rollbackprd:
      runs-on: ubuntu-latest
      needs: deploy-prd
      environment: production
      steps:
        
        - id: latestdel
          uses: thebritican/fetch-latest-release@v1.0.3
          with:
            github_token: ${{ secrets.PAT }}
        - name: getreleaseid  
          run: |
            release=$(curl \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.PAT }}" \
              https://api.github.com/repos/hirata11/convert/releases/tags/${{ steps.latestdel.outputs.tag_name }} | jq '.id')
            curl \
              -X DELETE \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.PAT }}" \
              https://api.github.com/repos/hirata11/convert/releases/$release   
        - id: latest
          uses: thebritican/fetch-latest-release@v1.0.3
          with:
            github_token: ${{ secrets.PAT }}        
        - name: Checkout private tools
          uses: actions/checkout@v3
          with:
            repository: hirata11/devops-template
            token: ${{ secrets.PAT }} # `GH_PAT` is a secret that contains your PAT
            path: template

        - name: templateDeploy  
          uses: ./template/deploy
          with:
            AZURE_CREDENTIALS:  ${{ secrets.AZURE_CREDENTIALS }}
            IMAGE: ${{ env.IMAGE }}
            ACR: ${{ env.ACR }}
            TAG: ${{ steps.latest.outputs.tag_name }}
  
