name: CI/CD

on: 
  release:
    types: [published, deleted]

env:
  DEPLOYMENT_NAME: convert-app # nome da aplicação.
  IMAGE: convert #nome da imagem
  ACR: ${{ secrets.REGISTRY_LOGIN_SERVER }}

jobs:

  buildTemplate:
    runs-on: ubuntu-latest
    steps:    
      - id: latest
        uses: thebritican/fetch-latest-release@v1.0.3
        with:
          github_token: ${{ secrets.PAT }}
  
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.latest.outputs.tag_name }}
          
      - name: Checkout private tools
        uses: actions/checkout@v3
        with:
          repository: hirata11/devops-template
          token: ${{ secrets.PAT }} # `GH_PAT` is a secret that contains your PAT
          path: template
        
      - name: templateBuiid  
        uses: ./template/build
        with:
          REGISTRY_LOGIN_SERVER:  ${{ secrets.REGISTRY_LOGIN_SERVER }}
          REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
          IMAGE: ${{ env.IMAGE }}
          ACR: ${{ env.ACR }}
          Env: $development
          tag: $GITHUB_RUN_NUMBER
          
  deploy-dev:
    runs-on: ubuntu-latest
    needs: buildTemplate
    environment: development
    steps:
      - name: Checkout private tools
        uses: actions/checkout@v3
        with:
          repository: hirata11/devops-template
          token: ${{ secrets.PAT }} # `GH_PAT` is a secret that contains your PAT
          path: template

      - name: templateDeploy  
        uses: ./template/deploy
        with:
          AZURE_CREDENTIALS:  ${{ secrets.AZURE_CREDENTIALS }}
          IMAGE: ${{ env.IMAGE }}
          ACR: ${{ env.ACR }}
          TAG: $GITHUB_RUN_NUMBER
          
  deploy-prd:
    runs-on: ubuntu-latest
    needs: deploy-dev
    environment: production
    steps:
      - name: Checkout private tools
        uses: actions/checkout@v3
        with:
          repository: hirata11/devops-template
          token: ${{ secrets.PAT }} # `GH_PAT` is a secret that contains your PAT
          path: template

      - name: templateDeploy  
        uses: ./template/deploy
        with:
          AZURE_CREDENTIALS:  ${{ secrets.AZURE_CREDENTIALS }}
          IMAGE: ${{ env.IMAGE }}
          ACR: ${{ env.ACR }}
          TAG: $GITHUB_RUN_NUMBER
